using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace appDevexpress
{
    public partial class Course_B_D : Form
    {
        int id;
        DataClasses1DataContext data = new DataClasses1DataContext();
        BL.Course_B_D co_b = new BL.Course_B_D();
        public Course_B_D()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {

        }

        private void propertyGridControl1_Click(object sender, EventArgs e)
        {

        }

        private void uPDETEToolStripButton_Click(object sender, EventArgs e)
        {
           

        }

        private void gETALLToolStripButton_Click(object sender, EventArgs e)
        {
          
        }

        private void Course_B_D_Load(object sender, EventArgs e)
        {
            dataGridView1.DataSource = co_b.GET_ALL_Course_B_D();
            c.Properties.DataSource = data.Add_Courses;
            c.Properties.DisplayMember = "name";
            c.Properties.ValueMember = "course_code";

            i.Properties.DataSource = data.Intakes;
            i.Properties.DisplayMember = "num_intake";
            i.Properties.ValueMember = "Intake_code";

            d.Properties.DataSource = data.View_Acadimics;
            d.Properties.DisplayMember = "first_name";
            d.Properties.ValueMember = "doctor_code";

            b.Properties.DataSource = data.Books;
            b.Properties.DisplayMember = "name";
            b.Properties.ValueMember = "ISPN";

            p.Properties.DataSource = data.Programs;
            p.Properties.DisplayMember = "name";
            p.Properties.ValueMember = "program_code";



        }

        private void gridView2_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {


        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (c.Text != "" && i.Text != "" && d.Text != "" && p.Text != "" && b.Text != "" && path.Text != "" && to.Text != "" && from.Text != "")
            {
                int c_c = Convert.ToInt32(c.EditValue);
                int d_c = Convert.ToInt32(d.EditValue);
                int p_c = Convert.ToInt32(p.EditValue);
                int i_c = Convert.ToInt32(i.EditValue);
                string b_c = b.EditValue.ToString();
                co_b.ADD_Course_B_D(c_c, d_c, i_c, b_c, p_c, from.Text, to.Text, path.Text);
                MetroFramework.MetroMessageBox.Show(this, "\n \n Done add  successfully", "Message", MessageBoxButtons.OK, MessageBoxIcon.Information);
                dataGridView1.DataSource = co_b.GET_ALL_Course_B_D();
            }
            else
            {
                MetroFramework.MetroMessageBox.Show(this, "\n \nMake sure of the textbox not null  :", "Message", MessageBoxButtons.OK, MessageBoxIcon.Information);

            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
             try
            {
                if (id != 0)
                {
                    if (c.Text != "" && d.Text != "" && i.Text != "" && from.Text != "" && p.Text != "" && path.Text != "" && to.Text != "")
                    {
                        int rc = Convert.ToInt32(c.EditValue);
                        int rd = Convert.ToInt32(d.EditValue);
                        int rp = Convert.ToInt32(p.EditValue);
                        int ri = Convert.ToInt32(i.EditValue);
                        string gb = b.EditValue.ToString();
                        co_b.UPDATE_Course_B_D(rc, rd, ri, gb, rp, from.Text, to.Text, path.Text, id);


                        MetroFramework.MetroMessageBox.Show(this, "\n \n Done Update successfully", "Message", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        this.dataGridView1.DataSource = co_b.GET_ALL_Course_B_D();
                    }
                    else
                    {
                        MetroFramework.MetroMessageBox.Show(this, "\n \nMake sure of the textbox not null or the Password like the Replay Password :", "Message", MessageBoxButtons.OK, MessageBoxIcon.Information);

                    }
                }
                else
                {

                    MetroFramework.MetroMessageBox.Show(this, "\n \n you most choose item to be update", "Message", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);

                }
            }
            catch (Exception ex)
            {
                MetroFramework.MetroMessageBox.Show(this, "Error :\n Number 1 " + ex.Message, "Error :\n", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            if (id != 0)
            {
                if (MetroFramework.MetroMessageBox.Show(this, "\n \n Are you sure to delete this item ?", "Message", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
                {
                    co_b.DELETE_Course_B_D(id);

                    MetroFramework.MetroMessageBox.Show(this, "\n \n Done delete successefuly", "Message", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    dataGridView1.DataSource = co_b.GET_ALL_Course_B_D();
                }
                else
                {
                    MetroFramework.MetroMessageBox.Show(this, "\n \n Done delete cancel", "Message", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);

                }
            }
            else
            {

                MetroFramework.MetroMessageBox.Show(this, "\n \n you most choose item to be delete", "Message", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);

            }
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void path_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            OpenFileDialog p = new OpenFileDialog();
            p.ShowDialog();
            path.Text = p.FileName.ToString();
            
        }

        private void d_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void b_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            
           
        }

        private void dataGridView1_DoubleClick(object sender, EventArgs e)
        {
            
        }

        private void dataGridView1_Click(object sender, EventArgs e)
        {
            id = Convert.ToInt32(dataGridView1.CurrentRow.Cells[0].Value.ToString());
            this.c.Text = dataGridView1.CurrentRow.Cells[1].Value.ToString();
            this.d.Text = dataGridView1.CurrentRow.Cells[2].Value.ToString();
            this.i.Text = dataGridView1.CurrentRow.Cells[4].Value.ToString();
            this.p.Text = dataGridView1.CurrentRow.Cells[3].Value.ToString();
            this.b.Text = dataGridView1.CurrentRow.Cells[5].Value.ToString();
            this.from.Text = dataGridView1.CurrentRow.Cells[6].Value.ToString();
            this.to.Text = dataGridView1.CurrentRow.Cells[7].Value.ToString();
            this.path.Text = dataGridView1.CurrentRow.Cells[8].Value.ToString();
        }
    }
}